# Generated by Django 5.2.17 on 2026-08-18 02:45

import common.db.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationEntry',
            fields=[
                ('id', models.UUIDField(default=common.db.models.generate_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField()),
                ('locale', models.CharField(max_length=10)),
                ('field', models.CharField(max_length=50)),
                ('value', models.TextField()),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'translation_entry',
                'indexes': [models.Index(fields=['content_type', 'object_id', 'locale'], name='translation_content_9375a3_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'locale', 'field'), name='unique_translation_entry_per_field_locale')],
            },
        ),
    ]
