# Generated by Django 5.2.17 on 2026-08-13 14:46

import common.db.models
import django.contrib.postgres.fields
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportedCountry',
            fields=[
                ('id', models.UUIDField(default=common.db.models.generate_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', django_countries.fields.CountryField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('default_locale', models.CharField(max_length=10)),
                ('allowed_locales', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None)),
                ('allowed_currencies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), size=None)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'localization_supported_country',
            },
        ),
    ]
