# Generated by Django 5.2.17 on 2026-08-13 14:52

import common.db.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=common.db.models.generate_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'accounts_customer',
            },
        ),
        migrations.CreateModel(
            name='VerificationToken',
            fields=[
                ('id', models.UUIDField(default=common.db.models.generate_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(choices=[('email_verification', 'Email verification'), ('password_reset', 'Password reset'), ('email_change', 'Email change')], max_length=30)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('new_email', models.EmailField(blank=True, max_length=254)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_tokens', to='accounts.customer')),
            ],
            options={
                'db_table': 'accounts_verification_token',
            },
        ),
        migrations.CreateModel(
            name='LoginMethod',
            fields=[
                ('id', models.UUIDField(default=common.db.models.generate_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('password', 'Password'), ('google', 'Google')], max_length=20)),
                ('password_hash', models.CharField(blank=True, max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_methods', to='accounts.customer')),
            ],
            options={
                'db_table': 'accounts_login_method',
                'constraints': [models.UniqueConstraint(fields=('customer', 'provider'), name='unique_customer_login_method_provider')],
            },
        ),
    ]
