# Generated by Django 5.2.17 on 2026-08-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginmethod',
            name='provider_subject_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name='loginmethod',
            constraint=models.UniqueConstraint(condition=models.Q(('provider', 'google')), fields=('provider', 'provider_subject_id'), name='unique_google_provider_subject_id'),
        ),
    ]
