# Generated by Django 5.2.17 on 2026-08-13 15:27

import common.db.models
import django.db.models.deletion
import modules.accounts.models.mfa_device
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_loginmethod_provider_subject_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=common.db.models.generate_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('master_admin', 'Master Admin'), ('store_manager', 'Store Manager'), ('order_staff', 'Order Staff')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'accounts_staff',
            },
        ),
        migrations.CreateModel(
            name='StaffTOTPDevice',
            fields=[
                ('id', models.UUIDField(default=common.db.models.generate_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(default=modules.accounts.models.mfa_device._generate_totp_key, help_text='Hex-encoded shared secret.', max_length=80)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='totp_device', to='accounts.staff')),
            ],
            options={
                'db_table': 'accounts_staff_totp_device',
            },
        ),
    ]
