# Generated by Django 5.2.17 on 2026-08-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_staff_stafftotpdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='preferred_currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_locale',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
