# Generated by Django 5.2.17 on 2026-08-18 03:36

import common.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaUpload',
            fields=[
                ('id', models.UUIDField(default=common.db.models.generate_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('storage_key', models.CharField(max_length=255, unique=True)),
                ('declared_content_type', models.CharField(max_length=100)),
                ('declared_size_bytes', models.PositiveBigIntegerField()),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'media_upload',
            },
        ),
    ]
