# Generated by Django 5.2.17 on 2026-08-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaupload',
            name='avif_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mediaupload',
            name='thumbnail_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mediaupload',
            name='webp_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
