# Generated by Django 5.2.17 on 2026-08-18 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_attribute_attributevalue_variantattributevalue_and_more'),
        ('media', '0002_mediaupload_avif_key_mediaupload_thumbnail_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaupload',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_uploads', to='catalog.product'),
        ),
    ]
