# Generated by Django 5.2.17 on 2026-08-18 08:49

import common.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.UUIDField(default=common.db.models.generate_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_currency', models.CharField(max_length=3)),
                ('target_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('source', models.CharField(max_length=100)),
                ('fetched_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'pricing_exchange_rate',
                'indexes': [models.Index(fields=['base_currency', 'target_currency', '-fetched_at'], name='pricing_exc_base_cu_f2d0c4_idx')],
                'constraints': [models.UniqueConstraint(fields=('base_currency', 'target_currency', 'fetched_at'), name='unique_exchange_rate_snapshot')],
            },
        ),
    ]
