# Generated by Django 5.2.17 on 2026-08-18 02:37

import common.db.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_brand_product_productcategory_product_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.UUIDField(default=common.db.models.generate_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
            ],
            options={
                'db_table': 'catalog_attribute',
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.UUIDField(default=common.db.models.generate_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField()),
            ],
            options={
                'db_table': 'catalog_attribute_value',
            },
        ),
        migrations.CreateModel(
            name='VariantAttributeValue',
            fields=[
                ('id', models.UUIDField(default=common.db.models.generate_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'catalog_variant_attribute_value',
            },
        ),
        migrations.AddField(
            model_name='variant',
            name='attribute_combination_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.UniqueConstraint(condition=models.Q(('attribute_combination_key', ''), _negated=True), fields=('product', 'attribute_combination_key'), name='unique_attribute_combination_per_product'),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='catalog.attribute'),
        ),
        migrations.AddField(
            model_name='variantattributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.attribute'),
        ),
        migrations.AddField(
            model_name='variantattributevalue',
            name='attribute_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.attributevalue'),
        ),
        migrations.AddField(
            model_name='variantattributevalue',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='catalog.variant'),
        ),
        migrations.AddConstraint(
            model_name='attributevalue',
            constraint=models.UniqueConstraint(fields=('attribute', 'code'), name='unique_attribute_value_code_per_attribute'),
        ),
        migrations.AddConstraint(
            model_name='variantattributevalue',
            constraint=models.UniqueConstraint(fields=('variant', 'attribute'), name='unique_attribute_per_variant'),
        ),
    ]
