"""Shared abstract base model — UUIDv7 primary key + audit timestamps.

Every domain model under `modules/` inherits from this so the ID scheme and
created/updated columns stay identical across modules; no module
reimplements them.
"""

from __future__ import annotations

import uuid

from django.db import models

from common.ids.uuid7 import uuid7


def generate_id() -> uuid.UUID:
    """Indirection so Django's migration serializer points at this module.

    `common/ids/__init__.py` re-exports `uuid7` under the same dotted name
    as its submodule (`common.ids.uuid7`), which shadows the submodule once
    imported — the autogenerated migration's `common.ids.uuid7.uuid7`
    reference then resolves onto the function instead of the module. Using a
    function defined here instead sidesteps that.
    """
    return uuid7()


class BaseModel(models.Model):
    id = models.UUIDField(primary_key=True, default=generate_id, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class IdempotencyRecord(BaseModel):
    """Backs common/db/idempotency.py — guild.md §3.10/§6.2/§12.4. Defined
    here (not in idempotency.py) so Django's app model auto-discovery
    (`<app>/models.py`) picks it up.
    """

    actor_type = models.CharField(max_length=20)
    actor_id = models.CharField(max_length=64)
    action = models.CharField(max_length=100)
    idempotency_key = models.CharField(max_length=255)
    request_hash = models.CharField(max_length=64)
    response_status = models.PositiveSmallIntegerField()
    response_body = models.JSONField(null=True, blank=True)
    expires_at = models.DateTimeField()

    class Meta:
        app_label = "common_db"
        db_table = "idempotency_record"
        constraints = [
            models.UniqueConstraint(
                fields=["actor_type", "actor_id", "action", "idempotency_key"],
                name="unique_idempotency_key_per_actor_action",
            ),
        ]

    def __str__(self) -> str:
        return f"{self.action}:{self.idempotency_key}"
