"""Shared abstract base model — UUIDv7 primary key + audit timestamps.

Every domain model under `modules/` inherits from this so the ID scheme and
created/updated columns stay identical across modules; no module
reimplements them.
"""

from __future__ import annotations

import uuid

from django.db import models

from common.ids.uuid7 import uuid7


def generate_id() -> uuid.UUID:
    """Indirection so Django's migration serializer points at this module.

    `common/ids/__init__.py` re-exports `uuid7` under the same dotted name
    as its submodule (`common.ids.uuid7`), which shadows the submodule once
    imported — the autogenerated migration's `common.ids.uuid7.uuid7`
    reference then resolves onto the function instead of the module. Using a
    function defined here instead sidesteps that.
    """
    return uuid7()


class BaseModel(models.Model):
    id = models.UUIDField(primary_key=True, default=generate_id, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True
