# Generated by Django 5.2.17 on 2026-08-13 17:09

import common.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=common.db.models.generate_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_type', models.CharField(max_length=20)),
                ('actor_id', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=100)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('request_hash', models.CharField(max_length=64)),
                ('response_status', models.PositiveSmallIntegerField()),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'idempotency_record',
                'constraints': [models.UniqueConstraint(fields=('actor_type', 'actor_id', 'action', 'idempotency_key'), name='unique_idempotency_key_per_actor_action')],
            },
        ),
    ]
