# Generated by Django 5.2.17 on 2026-08-18 03:50

import common.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=common.db.models.generate_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'outbox_event',
            },
        ),
    ]
